In [1]:
!pip install xarray netCDF4 pandas numpy pyarrow openpyxl tqdm -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 39.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 31.3 MB/s eta 0:00:00

In [2]:
import re
import numpy as np
import pandas as pd
import xarray as xr
from pathlib import Path
from datetime import datetime, timedelta
from tqdm import tqdm

# ============================================================
# NASA MODIS-Aqua Level-3 8-day CHL via OPeNDAP
# Product: AQUA_MODIS L3m 8D CHL chlor_a 4km
# Variable: chlor_a
# ============================================================

OUTPUT_DIR = Path("modis_chlorophyll_data/processed")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

START_YEAR = 2020
END_YEAR = 2024

BASINS = {
    "Bay_of_Bengal": {
        "lat_min": 5.0,
        "lat_max": 22.0,
        "lon_min": 80.0,
        "lon_max": 98.0
    },
    "Arabian_Sea": {
        "lat_min": 5.0,
        "lat_max": 22.0,
        "lon_min": 60.0,
        "lon_max": 75.0
    }
}


def generate_8day_periods(year):
    start = datetime(year, 1, 1)
    end_year = datetime(year, 12, 31)

    periods = []
    current = start

    while current <= end_year:
        period_start = current
        period_end = min(current + timedelta(days=7), end_year)

        periods.append((period_start, period_end))

        current = period_end + timedelta(days=1)

    return periods


def build_opendap_url(period_start, period_end):
    year = period_start.strftime("%Y")
    mmdd = period_start.strftime("%m%d")

    start_str = period_start.strftime("%Y%m%d")
    end_str = period_end.strftime("%Y%m%d")

    filename = f"AQUA_MODIS.{start_str}_{end_str}.L3m.8D.CHL.chlor_a.4km.nc"

    url = (
        f"https://oceandata.sci.gsfc.nasa.gov/opendap/MODISA/L3SMI/"
        f"{year}/{mmdd}/{filename}"
    )

    return url, filename


def to_025_degree_grid(values):
    return np.floor(values / 0.25) * 0.25 + 0.125


def select_latlon_region(ds, lat_min, lat_max, lon_min, lon_max):
    # MODIS lat may be ascending or descending; handle both safely.
    lat_values = ds["lat"].values
    lon_values = ds["lon"].values

    if lat_values[0] > lat_values[-1]:
        lat_slice = slice(lat_max, lat_min)
    else:
        lat_slice = slice(lat_min, lat_max)

    if lon_values[0] > lon_values[-1]:
        lon_slice = slice(lon_max, lon_min)
    else:
        lon_slice = slice(lon_min, lon_max)

    return ds.sel(lat=lat_slice, lon=lon_slice)


def process_one_opendap_file(period_start, period_end):
    url, filename = build_opendap_url(period_start, period_end)

    print("\nProcessing:", filename)

    date_start = pd.to_datetime(period_start)
    date_end = pd.to_datetime(period_end)
    date_center = date_start + (date_end - date_start) / 2

    frames = []

    try:
        ds = xr.open_dataset(url, engine="netcdf4")

        if "chlor_a" not in ds.data_vars:
            print("chlor_a not found. Available variables:", list(ds.data_vars))
            ds.close()
            return pd.DataFrame()

        for basin_name, b in BASINS.items():
            try:
                sub = select_latlon_region(
                    ds,
                    b["lat_min"],
                    b["lat_max"],
                    b["lon_min"],
                    b["lon_max"]
                )

                # Load only the small regional subset
                chl = sub["chlor_a"].load()

                df = chl.to_dataframe().reset_index()

                df = df.rename(columns={
                    "lat": "latitude",
                    "lon": "longitude"
                })

                df["chlor_a"] = pd.to_numeric(df["chlor_a"], errors="coerce")

                # Clean invalid values
                df = df.replace([np.inf, -np.inf], np.nan)
                df = df.dropna(subset=["chlor_a"])
                df = df[df["chlor_a"] > 0].copy()

                if df.empty:
                    print("No valid chlorophyll for:", basin_name)
                    continue

                df["basin"] = basin_name
                df["date_start"] = date_start
                df["date_end"] = date_end
                df["date_center"] = date_center

                df["lat_025"] = to_025_degree_grid(df["latitude"])
                df["lon_025"] = to_025_degree_grid(df["longitude"])

                df_025 = (
                    df.groupby(
                        ["basin", "date_start", "date_end", "date_center", "lat_025", "lon_025"],
                        as_index=False
                    )
                    .agg(
                        chlor_a_mean=("chlor_a", "mean"),
                        chlor_a_median=("chlor_a", "median"),
                        chlor_a_std=("chlor_a", "std"),
                        chlor_a_min=("chlor_a", "min"),
                        chlor_a_max=("chlor_a", "max"),
                        valid_pixel_count=("chlor_a", "count")
                    )
                )

                frames.append(df_025)

                print(basin_name, "rows:", len(df_025))

            except Exception as e:
                print("Region failed:", basin_name)
                print("Reason:", e)

        ds.close()

    except Exception as e:
        print("Failed to open OPeNDAP file:")
        print(url)
        print("Reason:", e)
        return pd.DataFrame()

    if len(frames) == 0:
        return pd.DataFrame()

    return pd.concat(frames, ignore_index=True)

In [3]:
test_start = datetime(2020, 1, 1)
test_end = datetime(2020, 1, 8)

df_test = process_one_opendap_file(test_start, test_end)

print("Test shape:", df_test.shape)
df_test.head()

Processing: AQUA_MODIS.20200101_20200108.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3757
Arabian_Sea rows: 3744
Test shape: (7501, 12)

,basin,date_start,date_end,date_center,lat_025,lon_025,chlor_a_mean,chlor_a_median,chlor_a_std,chlor_a_min,chlor_a_max,valid_pixel_count
0,Bay_of_Bengal,2020-01-01,2020-01-08,2020-01-04 12:00:00,5.125,80.125,0.258539,0.264737,0.042121,0.172192,0.349827,36
1,Bay_of_Bengal,2020-01-01,2020-01-08,2020-01-04 12:00:00,5.125,80.375,0.176654,0.175468,0.015453,0.128524,0.226184,36
2,Bay_of_Bengal,2020-01-01,2020-01-08,2020-01-04 12:00:00,5.125,80.625,0.166483,0.175305,0.022700,0.118447,0.199029,36
3,Bay_of_Bengal,2020-01-01,2020-01-08,2020-01-04 12:00:00,5.125,80.875,0.154920,0.152771,0.023633,0.106967,0.200826,36
4,Bay_of_Bengal,2020-01-01,2020-01-08,2020-01-04 12:00:00,5.125,81.125,0.144689,0.142248,0.024714,0.108827,0.227319,35

In [4]:
all_frames = []
failed_periods = []

for year in range(START_YEAR, END_YEAR + 1):
    periods = generate_8day_periods(year)

    for period_start, period_end in tqdm(periods, desc=f"Year {year}"):
        df_temp = process_one_opendap_file(period_start, period_end)

        if df_temp.empty:
            failed_periods.append((period_start, period_end))
        else:
            all_frames.append(df_temp)

if len(all_frames) == 0:
    raise ValueError("No MODIS chlorophyll data processed. Check OPeNDAP access.")

modis_chl_025 = pd.concat(all_frames, ignore_index=True)

print("Final MODIS chlorophyll shape:", modis_chl_025.shape)
print("Failed periods:", len(failed_periods))

modis_chl_025.head()

Year 2020:   0%|          | 0/46 [00:00<?, ?it/s]

Processing: AQUA_MODIS.20200101_20200108.L3m.8D.CHL.chlor_a.4km.nc

Year 2020:   2%|▏         | 1/46 [00:01<00:47,  1.07s/it]

Bay_of_Bengal rows: 3757
Arabian_Sea rows: 3744

Processing: AQUA_MODIS.20200109_20200116.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3822

Year 2020:   4%|▍         | 2/46 [00:02<00:51,  1.18s/it]

Arabian_Sea rows: 3728

Processing: AQUA_MODIS.20200117_20200124.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3893

Year 2020:   7%|▋         | 3/46 [00:04<01:03,  1.47s/it]

Arabian_Sea rows: 3696

Processing: AQUA_MODIS.20200125_20200201.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3749

Year 2020:   9%|▊         | 4/46 [00:05<01:07,  1.60s/it]

Arabian_Sea rows: 3516

Processing: AQUA_MODIS.20200202_20200209.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3400

Year 2020:  11%|█         | 5/46 [00:07<01:00,  1.48s/it]

Arabian_Sea rows: 3778

Processing: AQUA_MODIS.20200210_20200217.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3914

Year 2020:  13%|█▎        | 6/46 [00:08<00:57,  1.45s/it]

Arabian_Sea rows: 3647

Processing: AQUA_MODIS.20200218_20200225.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3685

Year 2020:  15%|█▌        | 7/46 [00:09<00:54,  1.40s/it]

Arabian_Sea rows: 3645

Processing: AQUA_MODIS.20200226_20200304.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3585

Year 2020:  17%|█▋        | 8/46 [00:11<00:56,  1.48s/it]

Arabian_Sea rows: 3424

Processing: AQUA_MODIS.20200305_20200312.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3892

Year 2020:  20%|█▉        | 9/46 [00:12<00:50,  1.37s/it]

Arabian_Sea rows: 3817

Processing: AQUA_MODIS.20200313_20200320.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3770

Year 2020:  22%|██▏       | 10/46 [00:13<00:48,  1.35s/it]

Arabian_Sea rows: 3684

Processing: AQUA_MODIS.20200321_20200328.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3756

Year 2020:  24%|██▍       | 11/46 [00:15<00:44,  1.26s/it]

Arabian_Sea rows: 3564

Processing: AQUA_MODIS.20200329_20200405.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3663

Year 2020:  26%|██▌       | 12/46 [00:16<00:41,  1.23s/it]

Arabian_Sea rows: 3463

Processing: AQUA_MODIS.20200406_20200413.L3m.8D.CHL.chlor_a.4km.nc

Year 2020:  28%|██▊       | 13/46 [00:17<00:40,  1.24s/it]

Bay_of_Bengal rows: 3558
Arabian_Sea rows: 3550

Processing: AQUA_MODIS.20200414_20200421.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3556

Year 2020:  30%|███       | 14/46 [00:18<00:40,  1.26s/it]

Arabian_Sea rows: 3219

Processing: AQUA_MODIS.20200422_20200429.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3155

Year 2020:  33%|███▎      | 15/46 [00:20<00:42,  1.37s/it]

Arabian_Sea rows: 3307

Processing: AQUA_MODIS.20200430_20200507.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3399

Year 2020:  35%|███▍      | 16/46 [00:21<00:40,  1.37s/it]

Arabian_Sea rows: 3017

Processing: AQUA_MODIS.20200508_20200515.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3701

Year 2020:  37%|███▋      | 17/46 [00:22<00:38,  1.33s/it]

Arabian_Sea rows: 2689

Processing: AQUA_MODIS.20200516_20200523.L3m.8D.CHL.chlor_a.4km.nc

Year 2020:  39%|███▉      | 18/46 [00:23<00:34,  1.22s/it]

Bay_of_Bengal rows: 951
Arabian_Sea rows: 2905

Processing: AQUA_MODIS.20200524_20200531.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2946

Year 2020:  41%|████▏     | 19/46 [00:25<00:31,  1.17s/it]

Arabian_Sea rows: 3090

Processing: AQUA_MODIS.20200601_20200608.L3m.8D.CHL.chlor_a.4km.nc

Year 2020:  43%|████▎     | 20/46 [00:26<00:29,  1.15s/it]

Bay_of_Bengal rows: 2548
Arabian_Sea rows: 789

Processing: AQUA_MODIS.20200609_20200616.L3m.8D.CHL.chlor_a.4km.nc

Year 2020:  46%|████▌     | 21/46 [00:27<00:28,  1.13s/it]

Bay_of_Bengal rows: 1727
Arabian_Sea rows: 1084

Processing: AQUA_MODIS.20200617_20200624.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2441

Year 2020:  48%|████▊     | 22/46 [00:28<00:29,  1.23s/it]

Arabian_Sea rows: 607

Processing: AQUA_MODIS.20200625_20200702.L3m.8D.CHL.chlor_a.4km.nc

Year 2020:  50%|█████     | 23/46 [00:29<00:27,  1.21s/it]

Bay_of_Bengal rows: 2686
Arabian_Sea rows: 1310

Processing: AQUA_MODIS.20200703_20200710.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2415

Year 2020:  52%|█████▏    | 24/46 [00:31<00:26,  1.21s/it]

Arabian_Sea rows: 931

Processing: AQUA_MODIS.20200711_20200718.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2174

Year 2020:  54%|█████▍    | 25/46 [00:32<00:25,  1.20s/it]

Arabian_Sea rows: 514

Processing: AQUA_MODIS.20200719_20200726.L3m.8D.CHL.chlor_a.4km.nc

Year 2020:  57%|█████▋    | 26/46 [00:33<00:23,  1.19s/it]

Bay_of_Bengal rows: 3227
Arabian_Sea rows: 478

Processing: AQUA_MODIS.20200727_20200803.L3m.8D.CHL.chlor_a.4km.nc

Year 2020:  59%|█████▊    | 27/46 [00:34<00:22,  1.17s/it]

Bay_of_Bengal rows: 1854
Arabian_Sea rows: 1387

Processing: AQUA_MODIS.20200804_20200811.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 1356

Year 2020:  61%|██████    | 28/46 [00:35<00:20,  1.16s/it]

Arabian_Sea rows: 218

Processing: AQUA_MODIS.20200812_20200819.L3m.8D.CHL.chlor_a.4km.nc

Year 2020:  63%|██████▎   | 29/46 [00:36<00:18,  1.11s/it]

Bay_of_Bengal rows: 1053
Arabian_Sea rows: 430

Processing: AQUA_MODIS.20200820_20200827.L3m.8D.CHL.chlor_a.4km.nc

Year 2020:  65%|██████▌   | 30/46 [00:37<00:17,  1.08s/it]

Bay_of_Bengal rows: 1080
Arabian_Sea rows: 23

Processing: AQUA_MODIS.20200828_20200904.L3m.8D.CHL.chlor_a.4km.nc

Year 2020:  67%|██████▋   | 31/46 [00:38<00:15,  1.06s/it]

Bay_of_Bengal rows: 2107
Arabian_Sea rows: 943

Processing: AQUA_MODIS.20200905_20200912.L3m.8D.CHL.chlor_a.4km.nc

Year 2020:  70%|██████▉   | 32/46 [00:40<00:16,  1.17s/it]

Bay_of_Bengal rows: 2523
Arabian_Sea rows: 1335

Processing: AQUA_MODIS.20200913_20200920.L3m.8D.CHL.chlor_a.4km.nc

Year 2020:  72%|███████▏  | 33/46 [00:41<00:15,  1.17s/it]

Bay_of_Bengal rows: 1588
Arabian_Sea rows: 1855

Processing: AQUA_MODIS.20200921_20200928.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 1792

Year 2020:  74%|███████▍  | 34/46 [00:42<00:14,  1.19s/it]

Arabian_Sea rows: 3139

Processing: AQUA_MODIS.20200929_20201006.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2221

Year 2020:  76%|███████▌  | 35/46 [00:43<00:13,  1.18s/it]

Arabian_Sea rows: 3797

Processing: AQUA_MODIS.20201007_20201014.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 1272

Year 2020:  78%|███████▊  | 36/46 [00:44<00:11,  1.14s/it]

Arabian_Sea rows: 2429

Processing: AQUA_MODIS.20201015_20201022.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2666

Year 2020:  80%|████████  | 37/46 [00:46<00:10,  1.19s/it]

Arabian_Sea rows: 3058

Processing: AQUA_MODIS.20201023_20201030.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2922

Year 2020:  83%|████████▎ | 38/46 [00:47<00:09,  1.21s/it]

Arabian_Sea rows: 3541

Processing: AQUA_MODIS.20201031_20201107.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3834

Year 2020:  85%|████████▍ | 39/46 [00:48<00:08,  1.24s/it]

Arabian_Sea rows: 3593

Processing: AQUA_MODIS.20201108_20201115.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3833

Year 2020:  87%|████████▋ | 40/46 [00:49<00:07,  1.27s/it]

Arabian_Sea rows: 3354

Processing: AQUA_MODIS.20201116_20201123.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3314

Year 2020:  89%|████████▉ | 41/46 [00:51<00:06,  1.24s/it]

Arabian_Sea rows: 3720

Processing: AQUA_MODIS.20201124_20201201.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3779

Year 2020:  91%|█████████▏| 42/46 [00:52<00:04,  1.25s/it]

Arabian_Sea rows: 3766

Processing: AQUA_MODIS.20201202_20201209.L3m.8D.CHL.chlor_a.4km.nc

Year 2020:  93%|█████████▎| 43/46 [00:53<00:03,  1.20s/it]

Bay_of_Bengal rows: 3851
Arabian_Sea rows: 3661

Processing: AQUA_MODIS.20201210_20201217.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3111

Year 2020:  96%|█████████▌| 44/46 [00:54<00:02,  1.20s/it]

Arabian_Sea rows: 3445

Processing: AQUA_MODIS.20201218_20201225.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2868

Year 2020:  98%|█████████▊| 45/46 [00:55<00:01,  1.17s/it]

Arabian_Sea rows: 3338

Processing: AQUA_MODIS.20201226_20201231.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3559

Year 2020: 100%|██████████| 46/46 [00:57<00:00,  1.24s/it]

Arabian_Sea rows: 3335

Year 2021:   0%|          | 0/46 [00:00<?, ?it/s]

Processing: AQUA_MODIS.20210101_20210108.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3849

Year 2021:   2%|▏         | 1/46 [00:01<01:01,  1.36s/it]

Arabian_Sea rows: 2906

Processing: AQUA_MODIS.20210109_20210116.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3222

Year 2021:   4%|▍         | 2/46 [00:02<00:54,  1.23s/it]

Arabian_Sea rows: 3251

Processing: AQUA_MODIS.20210117_20210124.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3739

Year 2021:   7%|▋         | 3/46 [00:03<00:50,  1.18s/it]

Arabian_Sea rows: 3807

Processing: AQUA_MODIS.20210125_20210201.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3355

Year 2021:   9%|▊         | 4/46 [00:04<00:50,  1.19s/it]

Arabian_Sea rows: 3560

Processing: AQUA_MODIS.20210202_20210209.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3542

Year 2021:  11%|█         | 5/46 [00:06<00:49,  1.21s/it]

Arabian_Sea rows: 3612

Processing: AQUA_MODIS.20210210_20210217.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3761

Year 2021:  13%|█▎        | 6/46 [00:07<00:48,  1.22s/it]

Arabian_Sea rows: 3730

Processing: AQUA_MODIS.20210218_20210225.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3444

Year 2021:  15%|█▌        | 7/46 [00:08<00:50,  1.30s/it]

Arabian_Sea rows: 3814

Processing: AQUA_MODIS.20210226_20210305.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3783

Year 2021:  17%|█▋        | 8/46 [00:10<00:51,  1.34s/it]

Arabian_Sea rows: 3304

Processing: AQUA_MODIS.20210306_20210313.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3589

Year 2021:  20%|█▉        | 9/46 [00:11<00:48,  1.31s/it]

Arabian_Sea rows: 3732

Processing: AQUA_MODIS.20210314_20210321.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2519

Year 2021:  22%|██▏       | 10/46 [00:12<00:47,  1.32s/it]

Arabian_Sea rows: 2523

Processing: AQUA_MODIS.20210322_20210329.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 1594

Year 2021:  24%|██▍       | 11/46 [00:14<00:46,  1.33s/it]

Arabian_Sea rows: 2230

Processing: AQUA_MODIS.20210330_20210406.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 890

Year 2021:  26%|██▌       | 12/46 [00:15<00:42,  1.25s/it]

Arabian_Sea rows: 3394

Processing: AQUA_MODIS.20210407_20210414.L3m.8D.CHL.chlor_a.4km.nc

Year 2021:  28%|██▊       | 13/46 [00:16<00:39,  1.20s/it]

Bay_of_Bengal rows: 3528
Arabian_Sea rows: 2662

Processing: AQUA_MODIS.20210415_20210422.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3513

Year 2021:  30%|███       | 14/46 [00:17<00:38,  1.21s/it]

Arabian_Sea rows: 3130

Processing: AQUA_MODIS.20210423_20210430.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3162

Year 2021:  33%|███▎      | 15/46 [00:18<00:36,  1.18s/it]

Arabian_Sea rows: 2900

Processing: AQUA_MODIS.20210501_20210508.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3655

Year 2021:  35%|███▍      | 16/46 [00:19<00:34,  1.15s/it]

Arabian_Sea rows: 2621

Processing: AQUA_MODIS.20210509_20210516.L3m.8D.CHL.chlor_a.4km.nc

Year 2021:  37%|███▋      | 17/46 [00:20<00:33,  1.17s/it]

Bay_of_Bengal rows: 3677
Arabian_Sea rows: 1416

Processing: AQUA_MODIS.20210517_20210524.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2570

Year 2021:  39%|███▉      | 18/46 [00:21<00:31,  1.12s/it]

Arabian_Sea rows: 1415

Processing: AQUA_MODIS.20210525_20210601.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 1392

Year 2021:  41%|████▏     | 19/46 [00:23<00:30,  1.14s/it]

Arabian_Sea rows: 1553

Processing: AQUA_MODIS.20210602_20210609.L3m.8D.CHL.chlor_a.4km.nc

Year 2021:  43%|████▎     | 20/46 [00:24<00:29,  1.12s/it]

Bay_of_Bengal rows: 2708
Arabian_Sea rows: 1304

Processing: AQUA_MODIS.20210610_20210617.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 1409

Year 2021:  46%|████▌     | 21/46 [00:25<00:29,  1.16s/it]

Arabian_Sea rows: 1264

Processing: AQUA_MODIS.20210618_20210625.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 1345

Year 2021:  48%|████▊     | 22/46 [00:26<00:27,  1.13s/it]

Arabian_Sea rows: 825

Processing: AQUA_MODIS.20210626_20210703.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2781

Year 2021:  50%|█████     | 23/46 [00:27<00:27,  1.18s/it]

Arabian_Sea rows: 2004

Processing: AQUA_MODIS.20210704_20210711.L3m.8D.CHL.chlor_a.4km.nc

Year 2021:  52%|█████▏    | 24/46 [00:28<00:24,  1.11s/it]

Bay_of_Bengal rows: 2130
Arabian_Sea rows: 700

Processing: AQUA_MODIS.20210712_20210719.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2280

Year 2021:  54%|█████▍    | 25/46 [00:29<00:22,  1.10s/it]

Arabian_Sea rows: 1293

Processing: AQUA_MODIS.20210720_20210727.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 1693
Arabian_Sea rows: 1022

Year 2021:  57%|█████▋    | 26/46 [00:30<00:21,  1.08s/it]

Processing: AQUA_MODIS.20210728_20210804.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 1372

Year 2021:  59%|█████▊    | 27/46 [00:32<00:20,  1.10s/it]

Arabian_Sea rows: 1726

Processing: AQUA_MODIS.20210805_20210812.L3m.8D.CHL.chlor_a.4km.nc

Year 2021:  61%|██████    | 28/46 [00:33<00:19,  1.08s/it]

Bay_of_Bengal rows: 1756
Arabian_Sea rows: 249

Processing: AQUA_MODIS.20210813_20210820.L3m.8D.CHL.chlor_a.4km.nc

Year 2021:  63%|██████▎   | 29/46 [00:34<00:18,  1.07s/it]

Bay_of_Bengal rows: 1475
Arabian_Sea rows: 951

Processing: AQUA_MODIS.20210821_20210828.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2667

Year 2021:  65%|██████▌   | 30/46 [00:35<00:17,  1.09s/it]

Arabian_Sea rows: 1837

Processing: AQUA_MODIS.20210829_20210905.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 1477

Year 2021:  67%|██████▋   | 31/46 [00:36<00:16,  1.08s/it]

Arabian_Sea rows: 1549

Processing: AQUA_MODIS.20210906_20210913.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 1997

Year 2021:  70%|██████▉   | 32/46 [00:37<00:15,  1.12s/it]

Arabian_Sea rows: 1314

Processing: AQUA_MODIS.20210914_20210921.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 1807

Year 2021:  72%|███████▏  | 33/46 [00:38<00:14,  1.14s/it]

Arabian_Sea rows: 2052

Processing: AQUA_MODIS.20210922_20210929.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2269

Year 2021:  74%|███████▍  | 34/46 [00:39<00:13,  1.13s/it]

Arabian_Sea rows: 1734

Processing: AQUA_MODIS.20210930_20211007.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3457

Year 2021:  76%|███████▌  | 35/46 [00:41<00:12,  1.18s/it]

Arabian_Sea rows: 3283

Processing: AQUA_MODIS.20211008_20211015.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 1827

Year 2021:  78%|███████▊  | 36/46 [00:42<00:11,  1.15s/it]

Arabian_Sea rows: 3039

Processing: AQUA_MODIS.20211016_20211023.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3210
Arabian_Sea rows: 3449

Year 2021:  80%|████████  | 37/46 [00:43<00:10,  1.15s/it]

Processing: AQUA_MODIS.20211024_20211031.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3273

Year 2021:  83%|████████▎ | 38/46 [00:44<00:09,  1.18s/it]

Arabian_Sea rows: 3674

Processing: AQUA_MODIS.20211101_20211108.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3159

Year 2021:  85%|████████▍ | 39/46 [00:45<00:08,  1.20s/it]

Arabian_Sea rows: 2865

Processing: AQUA_MODIS.20211109_20211116.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2875

Year 2021:  87%|████████▋ | 40/46 [00:47<00:07,  1.22s/it]

Arabian_Sea rows: 2554

Processing: AQUA_MODIS.20211117_20211124.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3789

Year 2021:  89%|████████▉ | 41/46 [00:48<00:05,  1.17s/it]

Arabian_Sea rows: 3552

Processing: AQUA_MODIS.20211125_20211202.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3660

Year 2021:  91%|█████████▏| 42/46 [00:49<00:04,  1.18s/it]

Arabian_Sea rows: 3620

Processing: AQUA_MODIS.20211203_20211210.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3931

Year 2021:  93%|█████████▎| 43/46 [00:50<00:03,  1.27s/it]

Arabian_Sea rows: 3726

Processing: AQUA_MODIS.20211211_20211218.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3690

Year 2021:  96%|█████████▌| 44/46 [00:51<00:02,  1.24s/it]

Arabian_Sea rows: 3595

Processing: AQUA_MODIS.20211219_20211226.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3615

Year 2021:  98%|█████████▊| 45/46 [00:53<00:01,  1.28s/it]

Arabian_Sea rows: 3726

Processing: AQUA_MODIS.20211227_20211231.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3675

Year 2021: 100%|██████████| 46/46 [00:54<00:00,  1.18s/it]

Arabian_Sea rows: 3184

Year 2022:   0%|          | 0/46 [00:00<?, ?it/s]

Processing: AQUA_MODIS.20220101_20220108.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3829

Year 2022:   2%|▏         | 1/46 [00:01<01:03,  1.41s/it]

Arabian_Sea rows: 3749

Processing: AQUA_MODIS.20220109_20220116.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3968

Year 2022:   4%|▍         | 2/46 [00:02<00:57,  1.31s/it]

Arabian_Sea rows: 3803

Processing: AQUA_MODIS.20220117_20220124.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3666

Year 2022:   7%|▋         | 3/46 [00:03<00:53,  1.25s/it]

Arabian_Sea rows: 3554

Processing: AQUA_MODIS.20220125_20220201.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3818

Year 2022:   9%|▊         | 4/46 [00:04<00:51,  1.21s/it]

Arabian_Sea rows: 3729

Processing: AQUA_MODIS.20220202_20220209.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3790

Year 2022:  11%|█         | 5/46 [00:06<00:50,  1.23s/it]

Arabian_Sea rows: 3799

Processing: AQUA_MODIS.20220210_20220217.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3198

Year 2022:  13%|█▎        | 6/46 [00:07<00:47,  1.18s/it]

Arabian_Sea rows: 3601

Processing: AQUA_MODIS.20220218_20220225.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3863

Year 2022:  15%|█▌        | 7/46 [00:08<00:48,  1.25s/it]

Arabian_Sea rows: 3660

Processing: AQUA_MODIS.20220226_20220305.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3480

Year 2022:  17%|█▋        | 8/46 [00:09<00:45,  1.21s/it]

Arabian_Sea rows: 3653

Processing: AQUA_MODIS.20220306_20220313.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3575

Year 2022:  20%|█▉        | 9/46 [00:11<00:45,  1.22s/it]

Arabian_Sea rows: 3158

Processing: AQUA_MODIS.20220314_20220321.L3m.8D.CHL.chlor_a.4km.nc

Year 2022:  22%|██▏       | 10/46 [00:12<00:41,  1.14s/it]

Bay_of_Bengal rows: 2848
Arabian_Sea rows: 2254

Processing: AQUA_MODIS.20220322_20220329.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2938

Year 2022:  24%|██▍       | 11/46 [00:13<00:40,  1.16s/it]

Arabian_Sea rows: 2346

Processing: AQUA_MODIS.20220330_20220406.L3m.8D.CHL.chlor_a.4km.nc

Year 2022:  26%|██▌       | 12/46 [00:14<00:38,  1.12s/it]

Bay_of_Bengal rows: 1786
Arabian_Sea rows: 560

Processing: AQUA_MODIS.20220407_20220414.L3m.8D.CHL.chlor_a.4km.nc

Year 2022:  28%|██▊       | 13/46 [00:15<00:35,  1.06s/it]

No valid chlorophyll for: Bay_of_Bengal
No valid chlorophyll for: Arabian_Sea

Processing: AQUA_MODIS.20220415_20220422.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2986

Year 2022:  30%|███       | 14/46 [00:16<00:35,  1.11s/it]

Arabian_Sea rows: 3307

Processing: AQUA_MODIS.20220423_20220430.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2462

Year 2022:  33%|███▎      | 15/46 [00:17<00:35,  1.14s/it]

Arabian_Sea rows: 2883

Processing: AQUA_MODIS.20220501_20220508.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 1915

Year 2022:  35%|███▍      | 16/46 [00:18<00:34,  1.14s/it]

Arabian_Sea rows: 1854

Processing: AQUA_MODIS.20220509_20220516.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 1935

Year 2022:  37%|███▋      | 17/46 [00:19<00:33,  1.16s/it]

Arabian_Sea rows: 657

Processing: AQUA_MODIS.20220517_20220524.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 1979

Year 2022:  39%|███▉      | 18/46 [00:21<00:33,  1.20s/it]

Arabian_Sea rows: 1077

Processing: AQUA_MODIS.20220525_20220601.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 1216
Arabian_Sea rows: 1306

Year 2022:  41%|████▏     | 19/46 [00:22<00:31,  1.16s/it]

Processing: AQUA_MODIS.20220602_20220609.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 582

Year 2022:  43%|████▎     | 20/46 [00:23<00:29,  1.14s/it]

Arabian_Sea rows: 1889

Processing: AQUA_MODIS.20220610_20220617.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2211

Year 2022:  46%|████▌     | 21/46 [00:24<00:28,  1.12s/it]

Arabian_Sea rows: 780

Processing: AQUA_MODIS.20220618_20220625.L3m.8D.CHL.chlor_a.4km.nc

Year 2022:  48%|████▊     | 22/46 [00:25<00:27,  1.13s/it]

Bay_of_Bengal rows: 2999
Arabian_Sea rows: 685

Processing: AQUA_MODIS.20220626_20220703.L3m.8D.CHL.chlor_a.4km.nc

Year 2022:  50%|█████     | 23/46 [00:26<00:24,  1.08s/it]

Bay_of_Bengal rows: 2028
Arabian_Sea rows: 691

Processing: AQUA_MODIS.20220704_20220711.L3m.8D.CHL.chlor_a.4km.nc

Year 2022:  52%|█████▏    | 24/46 [00:27<00:23,  1.08s/it]

Bay_of_Bengal rows: 597
Arabian_Sea rows: 79

Processing: AQUA_MODIS.20220712_20220719.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2378

Year 2022:  54%|█████▍    | 25/46 [00:28<00:22,  1.06s/it]

Arabian_Sea rows: 760

Processing: AQUA_MODIS.20220720_20220727.L3m.8D.CHL.chlor_a.4km.nc

Year 2022:  57%|█████▋    | 26/46 [00:29<00:21,  1.07s/it]

Bay_of_Bengal rows: 2382
Arabian_Sea rows: 1084

Processing: AQUA_MODIS.20220728_20220804.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2722

Year 2022:  59%|█████▊    | 27/46 [00:30<00:20,  1.07s/it]

Arabian_Sea rows: 1502

Processing: AQUA_MODIS.20220805_20220812.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 1314

Year 2022:  61%|██████    | 28/46 [00:32<00:19,  1.09s/it]

Arabian_Sea rows: 1034

Processing: AQUA_MODIS.20220813_20220820.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2164

Year 2022:  63%|██████▎   | 29/46 [00:33<00:19,  1.13s/it]

Arabian_Sea rows: 1575

Processing: AQUA_MODIS.20220821_20220828.L3m.8D.CHL.chlor_a.4km.nc

Year 2022:  65%|██████▌   | 30/46 [00:34<00:17,  1.11s/it]

Bay_of_Bengal rows: 1645
Arabian_Sea rows: 599

Processing: AQUA_MODIS.20220829_20220905.L3m.8D.CHL.chlor_a.4km.nc

Year 2022:  67%|██████▋   | 31/46 [00:35<00:16,  1.13s/it]

Bay_of_Bengal rows: 3175
Arabian_Sea rows: 1829

Processing: AQUA_MODIS.20220906_20220913.L3m.8D.CHL.chlor_a.4km.nc

Year 2022:  70%|██████▉   | 32/46 [00:36<00:15,  1.13s/it]

Bay_of_Bengal rows: 1647
Arabian_Sea rows: 1166

Processing: AQUA_MODIS.20220914_20220921.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2466

Year 2022:  72%|███████▏  | 33/46 [00:37<00:14,  1.13s/it]

Arabian_Sea rows: 2620

Processing: AQUA_MODIS.20220922_20220929.L3m.8D.CHL.chlor_a.4km.nc

Year 2022:  74%|███████▍  | 34/46 [00:38<00:13,  1.11s/it]

Bay_of_Bengal rows: 2607
Arabian_Sea rows: 3629

Processing: AQUA_MODIS.20220930_20221007.L3m.8D.CHL.chlor_a.4km.nc

Year 2022:  76%|███████▌  | 35/46 [00:39<00:12,  1.12s/it]

Bay_of_Bengal rows: 1968
Arabian_Sea rows: 3001

Processing: AQUA_MODIS.20221008_20221015.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3595

Year 2022:  78%|███████▊  | 36/46 [00:41<00:11,  1.14s/it]

Arabian_Sea rows: 3343

Processing: AQUA_MODIS.20221016_20221023.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2387

Year 2022:  80%|████████  | 37/46 [00:42<00:10,  1.18s/it]

Arabian_Sea rows: 3599

Processing: AQUA_MODIS.20221024_20221031.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3598

Year 2022:  83%|████████▎ | 38/46 [00:43<00:09,  1.18s/it]

Arabian_Sea rows: 3780

Processing: AQUA_MODIS.20221101_20221108.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3295

Year 2022:  85%|████████▍ | 39/46 [00:45<00:09,  1.31s/it]

Arabian_Sea rows: 3666

Processing: AQUA_MODIS.20221109_20221116.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2823

Year 2022:  87%|████████▋ | 40/46 [00:46<00:07,  1.26s/it]

Arabian_Sea rows: 2742

Processing: AQUA_MODIS.20221117_20221124.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3103

Year 2022:  89%|████████▉ | 41/46 [00:47<00:06,  1.21s/it]

Arabian_Sea rows: 3639

Processing: AQUA_MODIS.20221125_20221202.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3894

Year 2022:  91%|█████████▏| 42/46 [00:48<00:04,  1.20s/it]

Arabian_Sea rows: 3413

Processing: AQUA_MODIS.20221203_20221210.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2699

Year 2022:  93%|█████████▎| 43/46 [00:49<00:03,  1.22s/it]

Arabian_Sea rows: 3211

Processing: AQUA_MODIS.20221211_20221218.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3146

Year 2022:  96%|█████████▌| 44/46 [00:50<00:02,  1.18s/it]

Arabian_Sea rows: 3703

Processing: AQUA_MODIS.20221219_20221226.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3173

Year 2022:  98%|█████████▊| 45/46 [00:52<00:01,  1.20s/it]

Arabian_Sea rows: 3613

Processing: AQUA_MODIS.20221227_20221231.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3635

Year 2022: 100%|██████████| 46/46 [00:53<00:00,  1.16s/it]

Arabian_Sea rows: 3750

Year 2023:   0%|          | 0/46 [00:00<?, ?it/s]

Processing: AQUA_MODIS.20230101_20230108.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3605

Year 2023:   2%|▏         | 1/46 [00:01<00:55,  1.23s/it]

Arabian_Sea rows: 3582

Processing: AQUA_MODIS.20230109_20230116.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3774

Year 2023:   4%|▍         | 2/46 [00:02<00:54,  1.23s/it]

Arabian_Sea rows: 3631

Processing: AQUA_MODIS.20230117_20230124.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2893

Year 2023:   7%|▋         | 3/46 [00:03<00:53,  1.24s/it]

Arabian_Sea rows: 3707

Processing: AQUA_MODIS.20230125_20230201.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2743

Year 2023:   9%|▊         | 4/46 [00:05<00:53,  1.27s/it]

Arabian_Sea rows: 3334

Processing: AQUA_MODIS.20230202_20230209.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3779

Year 2023:  11%|█         | 5/46 [00:06<00:51,  1.25s/it]

Arabian_Sea rows: 3417

Processing: AQUA_MODIS.20230210_20230217.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3812

Year 2023:  13%|█▎        | 6/46 [00:07<00:49,  1.23s/it]

Arabian_Sea rows: 3496

Processing: AQUA_MODIS.20230218_20230225.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3537

Year 2023:  15%|█▌        | 7/46 [00:08<00:48,  1.25s/it]

Arabian_Sea rows: 3727

Processing: AQUA_MODIS.20230226_20230305.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2985

Year 2023:  17%|█▋        | 8/46 [00:10<00:50,  1.34s/it]

Arabian_Sea rows: 3427

Processing: AQUA_MODIS.20230306_20230313.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2718

Year 2023:  20%|█▉        | 9/46 [00:11<00:48,  1.31s/it]

Arabian_Sea rows: 2628

Processing: AQUA_MODIS.20230314_20230321.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3320

Year 2023:  22%|██▏       | 10/46 [00:12<00:45,  1.26s/it]

Arabian_Sea rows: 3593

Processing: AQUA_MODIS.20230322_20230329.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3613

Year 2023:  24%|██▍       | 11/46 [00:13<00:43,  1.25s/it]

Arabian_Sea rows: 3614

Processing: AQUA_MODIS.20230330_20230406.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3673

Year 2023:  26%|██▌       | 12/46 [00:15<00:42,  1.26s/it]

Arabian_Sea rows: 3819

Processing: AQUA_MODIS.20230407_20230414.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3003

Year 2023:  28%|██▊       | 13/46 [00:16<00:43,  1.33s/it]

Arabian_Sea rows: 3177

Processing: AQUA_MODIS.20230415_20230422.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 1629

Year 2023:  30%|███       | 14/46 [00:17<00:41,  1.30s/it]

Arabian_Sea rows: 3469

Processing: AQUA_MODIS.20230423_20230430.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3158

Year 2023:  33%|███▎      | 15/46 [00:19<00:39,  1.28s/it]

Arabian_Sea rows: 3596

Processing: AQUA_MODIS.20230501_20230508.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3112

Year 2023:  35%|███▍      | 16/46 [00:20<00:36,  1.23s/it]

Arabian_Sea rows: 3265

Processing: AQUA_MODIS.20230509_20230516.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 1027

Year 2023:  37%|███▋      | 17/46 [00:21<00:34,  1.19s/it]

Arabian_Sea rows: 3365

Processing: AQUA_MODIS.20230517_20230524.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2410

Year 2023:  39%|███▉      | 18/46 [00:22<00:34,  1.22s/it]

Arabian_Sea rows: 3667

Processing: AQUA_MODIS.20230525_20230601.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 1723

Year 2023:  41%|████▏     | 19/46 [00:23<00:32,  1.20s/it]

Arabian_Sea rows: 3663

Processing: AQUA_MODIS.20230602_20230609.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 601

Year 2023:  43%|████▎     | 20/46 [00:24<00:30,  1.16s/it]

Arabian_Sea rows: 2176

Processing: AQUA_MODIS.20230610_20230617.L3m.8D.CHL.chlor_a.4km.nc

Year 2023:  46%|████▌     | 21/46 [00:25<00:27,  1.10s/it]

Bay_of_Bengal rows: 1234
Arabian_Sea rows: 1256

Processing: AQUA_MODIS.20230618_20230625.L3m.8D.CHL.chlor_a.4km.nc

Year 2023:  48%|████▊     | 22/46 [00:26<00:25,  1.08s/it]

Bay_of_Bengal rows: 1930
Arabian_Sea rows: 542

Processing: AQUA_MODIS.20230626_20230703.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2723
Arabian_Sea rows: 958

Year 2023:  50%|█████     | 23/46 [00:27<00:24,  1.06s/it]

Processing: AQUA_MODIS.20230704_20230711.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2007

Year 2023:  52%|█████▏    | 24/46 [00:29<00:25,  1.16s/it]

Arabian_Sea rows: 402

Processing: AQUA_MODIS.20230712_20230719.L3m.8D.CHL.chlor_a.4km.nc

Year 2023:  54%|█████▍    | 25/46 [00:30<00:24,  1.17s/it]

Bay_of_Bengal rows: 1882
Arabian_Sea rows: 989

Processing: AQUA_MODIS.20230720_20230727.L3m.8D.CHL.chlor_a.4km.nc

Year 2023:  57%|█████▋    | 26/46 [00:31<00:21,  1.10s/it]

Bay_of_Bengal rows: 2142
Arabian_Sea rows: 642

Processing: AQUA_MODIS.20230728_20230804.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 1005

Year 2023:  59%|█████▊    | 27/46 [00:32<00:20,  1.09s/it]

Arabian_Sea rows: 1274

Processing: AQUA_MODIS.20230805_20230812.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 1223

Year 2023:  61%|██████    | 28/46 [00:34<00:25,  1.40s/it]

Arabian_Sea rows: 1546

Processing: AQUA_MODIS.20230813_20230820.L3m.8D.CHL.chlor_a.4km.nc

Year 2023:  63%|██████▎   | 29/46 [00:35<00:23,  1.38s/it]

Bay_of_Bengal rows: 1908
Arabian_Sea rows: 1939

Processing: AQUA_MODIS.20230821_20230828.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 1978

Year 2023:  65%|██████▌   | 30/46 [00:36<00:20,  1.26s/it]

Arabian_Sea rows: 2456

Processing: AQUA_MODIS.20230829_20230905.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 658

Year 2023:  67%|██████▋   | 31/46 [00:37<00:18,  1.21s/it]

Arabian_Sea rows: 1244

Processing: AQUA_MODIS.20230906_20230913.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 1557

Year 2023:  70%|██████▉   | 32/46 [00:38<00:16,  1.15s/it]

Arabian_Sea rows: 2623

Processing: AQUA_MODIS.20230914_20230921.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2005

Year 2023:  72%|███████▏  | 33/46 [00:40<00:15,  1.16s/it]

Arabian_Sea rows: 1370

Processing: AQUA_MODIS.20230922_20230929.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2357

Year 2023:  74%|███████▍  | 34/46 [00:41<00:14,  1.23s/it]

Arabian_Sea rows: 2656

Processing: AQUA_MODIS.20230930_20231007.L3m.8D.CHL.chlor_a.4km.nc

Year 2023:  76%|███████▌  | 35/46 [00:42<00:13,  1.20s/it]

Bay_of_Bengal rows: 1742
Arabian_Sea rows: 3280

Processing: AQUA_MODIS.20231008_20231015.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2986

Year 2023:  78%|███████▊  | 36/46 [00:43<00:11,  1.16s/it]

Arabian_Sea rows: 3236

Processing: AQUA_MODIS.20231016_20231023.L3m.8D.CHL.chlor_a.4km.nc

Year 2023:  80%|████████  | 37/46 [00:44<00:10,  1.14s/it]

Bay_of_Bengal rows: 2725
Arabian_Sea rows: 2544

Processing: AQUA_MODIS.20231024_20231031.L3m.8D.CHL.chlor_a.4km.nc

Year 2023:  83%|████████▎ | 38/46 [00:45<00:09,  1.14s/it]

Bay_of_Bengal rows: 3490
Arabian_Sea rows: 1860

Processing: AQUA_MODIS.20231101_20231108.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3749

Year 2023:  85%|████████▍ | 39/46 [00:47<00:08,  1.17s/it]

Arabian_Sea rows: 2010

Processing: AQUA_MODIS.20231109_20231116.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2802

Year 2023:  87%|████████▋ | 40/46 [00:48<00:06,  1.15s/it]

Arabian_Sea rows: 3324

Processing: AQUA_MODIS.20231117_20231124.L3m.8D.CHL.chlor_a.4km.nc

Year 2023:  89%|████████▉ | 41/46 [00:49<00:05,  1.16s/it]

Bay_of_Bengal rows: 3795
Arabian_Sea rows: 2433

Processing: AQUA_MODIS.20231125_20231202.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2886

Year 2023:  91%|█████████▏| 42/46 [00:50<00:04,  1.17s/it]

Arabian_Sea rows: 3271

Processing: AQUA_MODIS.20231203_20231210.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3751

Year 2023:  93%|█████████▎| 43/46 [00:51<00:03,  1.19s/it]

Arabian_Sea rows: 2973

Processing: AQUA_MODIS.20231211_20231218.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3215

Year 2023:  96%|█████████▌| 44/46 [00:53<00:02,  1.23s/it]

Arabian_Sea rows: 3155

Processing: AQUA_MODIS.20231219_20231226.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3595

Year 2023:  98%|█████████▊| 45/46 [00:54<00:01,  1.26s/it]

Arabian_Sea rows: 2629

Processing: AQUA_MODIS.20231227_20231231.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3178

Year 2023: 100%|██████████| 46/46 [00:55<00:00,  1.21s/it]

Arabian_Sea rows: 2689

Year 2024:   0%|          | 0/46 [00:00<?, ?it/s]

Processing: AQUA_MODIS.20240101_20240108.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3353

Year 2024:   2%|▏         | 1/46 [00:01<00:51,  1.13s/it]

Arabian_Sea rows: 3500

Processing: AQUA_MODIS.20240109_20240116.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3209

Year 2024:   4%|▍         | 2/46 [00:02<00:51,  1.18s/it]

Arabian_Sea rows: 3603

Processing: AQUA_MODIS.20240117_20240124.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3423

Year 2024:   7%|▋         | 3/46 [00:03<00:49,  1.14s/it]

Arabian_Sea rows: 3732

Processing: AQUA_MODIS.20240125_20240201.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3673

Year 2024:   9%|▊         | 4/46 [00:04<00:48,  1.16s/it]

Arabian_Sea rows: 3591

Processing: AQUA_MODIS.20240202_20240209.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3643

Year 2024:  11%|█         | 5/46 [00:05<00:48,  1.18s/it]

Arabian_Sea rows: 3644

Processing: AQUA_MODIS.20240210_20240217.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3788

Year 2024:  13%|█▎        | 6/46 [00:07<00:47,  1.19s/it]

Arabian_Sea rows: 3441

Processing: AQUA_MODIS.20240218_20240225.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3504

Year 2024:  15%|█▌        | 7/46 [00:08<00:46,  1.19s/it]

Arabian_Sea rows: 3817

Processing: AQUA_MODIS.20240226_20240304.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3216

Year 2024:  17%|█▋        | 8/46 [00:09<00:47,  1.24s/it]

Arabian_Sea rows: 3360

Processing: AQUA_MODIS.20240305_20240312.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3116

Year 2024:  20%|█▉        | 9/46 [00:11<00:48,  1.31s/it]

Arabian_Sea rows: 3739

Processing: AQUA_MODIS.20240313_20240320.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2783

Year 2024:  22%|██▏       | 10/46 [00:12<00:45,  1.26s/it]

Arabian_Sea rows: 2944

Processing: AQUA_MODIS.20240321_20240328.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2785

Year 2024:  24%|██▍       | 11/46 [00:13<00:44,  1.26s/it]

Arabian_Sea rows: 2792

Processing: AQUA_MODIS.20240329_20240405.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3351

Year 2024:  26%|██▌       | 12/46 [00:14<00:42,  1.26s/it]

Arabian_Sea rows: 3465

Processing: AQUA_MODIS.20240406_20240413.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2350

Year 2024:  28%|██▊       | 13/46 [00:15<00:39,  1.20s/it]

Arabian_Sea rows: 3398

Processing: AQUA_MODIS.20240414_20240421.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2935

Year 2024:  30%|███       | 14/46 [00:17<00:38,  1.20s/it]

Arabian_Sea rows: 2933

Processing: AQUA_MODIS.20240422_20240429.L3m.8D.CHL.chlor_a.4km.nc

Year 2024:  33%|███▎      | 15/46 [00:18<00:36,  1.17s/it]

Bay_of_Bengal rows: 2792
Arabian_Sea rows: 2760

Processing: AQUA_MODIS.20240430_20240507.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3236

Year 2024:  35%|███▍      | 16/46 [00:19<00:36,  1.21s/it]

Arabian_Sea rows: 3102

Processing: AQUA_MODIS.20240508_20240515.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3585

Year 2024:  37%|███▋      | 17/46 [00:20<00:34,  1.19s/it]

Arabian_Sea rows: 3544

Processing: AQUA_MODIS.20240516_20240523.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2861

Year 2024:  39%|███▉      | 18/46 [00:21<00:32,  1.16s/it]

Arabian_Sea rows: 2157

Processing: AQUA_MODIS.20240524_20240531.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 684

Year 2024:  41%|████▏     | 19/46 [00:22<00:31,  1.18s/it]

Arabian_Sea rows: 718

Processing: AQUA_MODIS.20240601_20240608.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 1454

Year 2024:  43%|████▎     | 20/46 [00:24<00:31,  1.21s/it]

Arabian_Sea rows: 1762

Processing: AQUA_MODIS.20240609_20240616.L3m.8D.CHL.chlor_a.4km.nc

Year 2024:  46%|████▌     | 21/46 [00:25<00:28,  1.12s/it]

Bay_of_Bengal rows: 1871
Arabian_Sea rows: 1467

Processing: AQUA_MODIS.20240617_20240624.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 1198

Year 2024:  48%|████▊     | 22/46 [00:26<00:27,  1.13s/it]

Arabian_Sea rows: 878

Processing: AQUA_MODIS.20240625_20240702.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 1992

Year 2024:  50%|█████     | 23/46 [00:27<00:26,  1.14s/it]

Arabian_Sea rows: 697

Processing: AQUA_MODIS.20240703_20240710.L3m.8D.CHL.chlor_a.4km.nc

Year 2024:  52%|█████▏    | 24/46 [00:28<00:24,  1.13s/it]

Bay_of_Bengal rows: 1548
Arabian_Sea rows: 376

Processing: AQUA_MODIS.20240711_20240718.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 1058
Arabian_Sea rows: 220

Year 2024:  54%|█████▍    | 25/46 [00:29<00:22,  1.07s/it]

Processing: AQUA_MODIS.20240719_20240726.L3m.8D.CHL.chlor_a.4km.nc

Year 2024:  57%|█████▋    | 26/46 [00:30<00:21,  1.10s/it]

Bay_of_Bengal rows: 1365
Arabian_Sea rows: 296

Processing: AQUA_MODIS.20240727_20240803.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 779

Year 2024:  59%|█████▊    | 27/46 [00:31<00:20,  1.10s/it]

Arabian_Sea rows: 102

Processing: AQUA_MODIS.20240804_20240811.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2885

Year 2024:  61%|██████    | 28/46 [00:32<00:19,  1.11s/it]

Arabian_Sea rows: 827

Processing: AQUA_MODIS.20240812_20240819.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2729

Year 2024:  63%|██████▎   | 29/46 [00:33<00:19,  1.13s/it]

Arabian_Sea rows: 119

Processing: AQUA_MODIS.20240820_20240827.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 1460

Year 2024:  65%|██████▌   | 30/46 [00:35<00:18,  1.18s/it]

Arabian_Sea rows: 1618

Processing: AQUA_MODIS.20240828_20240904.L3m.8D.CHL.chlor_a.4km.nc

Year 2024:  67%|██████▋   | 31/46 [00:36<00:17,  1.14s/it]

Bay_of_Bengal rows: 1911
Arabian_Sea rows: 1370

Processing: AQUA_MODIS.20240905_20240912.L3m.8D.CHL.chlor_a.4km.nc

Year 2024:  70%|██████▉   | 32/46 [00:37<00:15,  1.13s/it]

Bay_of_Bengal rows: 1773
Arabian_Sea rows: 1196

Processing: AQUA_MODIS.20240913_20240920.L3m.8D.CHL.chlor_a.4km.nc

Year 2024:  72%|███████▏  | 33/46 [00:38<00:14,  1.12s/it]

Bay_of_Bengal rows: 1366
Arabian_Sea rows: 2995

Processing: AQUA_MODIS.20240921_20240928.L3m.8D.CHL.chlor_a.4km.nc

Year 2024:  74%|███████▍  | 34/46 [00:39<00:13,  1.13s/it]

Bay_of_Bengal rows: 3233
Arabian_Sea rows: 3157

Processing: AQUA_MODIS.20240929_20241006.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3179

Year 2024:  76%|███████▌  | 35/46 [00:40<00:12,  1.16s/it]

Arabian_Sea rows: 3372

Processing: AQUA_MODIS.20241007_20241014.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3507
Arabian_Sea rows: 1780

Year 2024:  78%|███████▊  | 36/46 [00:42<00:11,  1.16s/it]

Processing: AQUA_MODIS.20241015_20241022.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3625

Year 2024:  80%|████████  | 37/46 [00:43<00:10,  1.15s/it]

Arabian_Sea rows: 3640

Processing: AQUA_MODIS.20241023_20241030.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3009

Year 2024:  83%|████████▎ | 38/46 [00:44<00:09,  1.15s/it]

Arabian_Sea rows: 3500

Processing: AQUA_MODIS.20241031_20241107.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3770

Year 2024:  85%|████████▍ | 39/46 [00:45<00:08,  1.17s/it]

Arabian_Sea rows: 3218

Processing: AQUA_MODIS.20241108_20241115.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3830

Year 2024:  87%|████████▋ | 40/46 [00:47<00:07,  1.27s/it]

Arabian_Sea rows: 2351

Processing: AQUA_MODIS.20241116_20241123.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2612

Year 2024:  89%|████████▉ | 41/46 [00:48<00:06,  1.29s/it]

Arabian_Sea rows: 2025

Processing: AQUA_MODIS.20241124_20241201.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 1524

Year 2024:  91%|█████████▏| 42/46 [00:49<00:04,  1.24s/it]

Arabian_Sea rows: 1805

Processing: AQUA_MODIS.20241202_20241209.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 2997

Year 2024:  93%|█████████▎| 43/46 [00:50<00:03,  1.19s/it]

Arabian_Sea rows: 3526

Processing: AQUA_MODIS.20241210_20241217.L3m.8D.CHL.chlor_a.4km.nc

Year 2024:  96%|█████████▌| 44/46 [00:51<00:02,  1.18s/it]

Bay_of_Bengal rows: 2351
Arabian_Sea rows: 2791

Processing: AQUA_MODIS.20241218_20241225.L3m.8D.CHL.chlor_a.4km.nc

Year 2024:  98%|█████████▊| 45/46 [00:52<00:01,  1.16s/it]

Bay_of_Bengal rows: 3188
Arabian_Sea rows: 3388

Processing: AQUA_MODIS.20241226_20241231.L3m.8D.CHL.chlor_a.4km.nc
Bay_of_Bengal rows: 3084

Year 2024: 100%|██████████| 46/46 [00:54<00:00,  1.18s/it]

Arabian_Sea rows: 3006
Final MODIS chlorophyll shape: (1205694, 12)
Failed periods: 1

,basin,date_start,date_end,date_center,lat_025,lon_025,chlor_a_mean,chlor_a_median,chlor_a_std,chlor_a_min,chlor_a_max,valid_pixel_count
0,Bay_of_Bengal,2020-01-01,2020-01-08,2020-01-04 12:00:00,5.125,80.125,0.258539,0.264737,0.042121,0.172192,0.349827,36
1,Bay_of_Bengal,2020-01-01,2020-01-08,2020-01-04 12:00:00,5.125,80.375,0.176654,0.175468,0.015453,0.128524,0.226184,36
2,Bay_of_Bengal,2020-01-01,2020-01-08,2020-01-04 12:00:00,5.125,80.625,0.166483,0.175305,0.022700,0.118447,0.199029,36
3,Bay_of_Bengal,2020-01-01,2020-01-08,2020-01-04 12:00:00,5.125,80.875,0.154920,0.152771,0.023633,0.106967,0.200826,36
4,Bay_of_Bengal,2020-01-01,2020-01-08,2020-01-04 12:00:00,5.125,81.125,0.144689,0.142248,0.024714,0.108827,0.227319,35

In [5]:
final_csv = OUTPUT_DIR / "modis_aqua_chlorophyll_8day_025deg_bob_as_2020_2024.csv"
final_parquet = OUTPUT_DIR / "modis_aqua_chlorophyll_8day_025deg_bob_as_2020_2024.parquet"

modis_chl_025.to_csv(final_csv, index=False)
modis_chl_025.to_parquet(final_parquet, index=False)

print("Saved CSV:", final_csv)
print("Saved Parquet:", final_parquet)

Saved CSV: modis_chlorophyll_data/processed/modis_aqua_chlorophyll_8day_025deg_bob_as_2020_2024.csv
Saved Parquet: modis_chlorophyll_data/processed/modis_aqua_chlorophyll_8day_025deg_bob_as_2020_2024.parquet

In [6]:
summary = (
    modis_chl_025.groupby(["basin", "date_start", "date_end", "date_center"], as_index=False)
    .agg(
        chlor_a_mean=("chlor_a_mean", "mean"),
        chlor_a_median=("chlor_a_median", "median"),
        chlor_a_std=("chlor_a_mean", "std"),
        chlor_a_min=("chlor_a_min", "min"),
        chlor_a_max=("chlor_a_max", "max"),
        valid_grid_cells=("valid_pixel_count", "count"),
        total_valid_pixels=("valid_pixel_count", "sum")
    )
)

summary_csv = OUTPUT_DIR / "modis_aqua_chlorophyll_8day_basin_summary_2020_2024.csv"
summary_excel = OUTPUT_DIR / "modis_aqua_chlorophyll_8day_basin_summary_2020_2024.xlsx"
summary_parquet = OUTPUT_DIR / "modis_aqua_chlorophyll_8day_basin_summary_2020_2024.parquet"

summary.to_csv(summary_csv, index=False)
summary.to_excel(summary_excel, index=False)
summary.to_parquet(summary_parquet, index=False)

print("Saved summary Excel:", summary_excel)
summary.head()

Saved summary Excel: modis_chlorophyll_data/processed/modis_aqua_chlorophyll_8day_basin_summary_2020_2024.xlsx

,basin,date_start,date_end,date_center,chlor_a_mean,chlor_a_median,chlor_a_std,chlor_a_min,chlor_a_max,valid_grid_cells,total_valid_pixels
0,Arabian_Sea,2020-01-01,2020-01-08,2020-01-04 12:00:00,0.415299,0.218771,1.013869,0.037991,53.132027,3744,126588
1,Arabian_Sea,2020-01-09,2020-01-16,2020-01-12 12:00:00,0.423762,0.229910,0.867328,0.033321,24.580702,3728,122933
2,Arabian_Sea,2020-01-17,2020-01-24,2020-01-20 12:00:00,0.563309,0.268910,1.350251,0.031221,39.372906,3696,120835
3,Arabian_Sea,2020-01-25,2020-02-01,2020-01-28 12:00:00,0.626203,0.274346,2.278628,0.059041,75.168282,3516,110424
4,Arabian_Sea,2020-02-02,2020-02-09,2020-02-05 12:00:00,0.623468,0.225414,1.969515,0.034876,82.651932,3778,122667

In [7]:
import shutil
from google.colab import files

zip_name = "modis_aqua_chlorophyll_2020_2024_processed"

shutil.make_archive(zip_name, "zip", "modis_chlorophyll_data")

files.download(zip_name + ".zip")