In [1]:
!pip install copernicusmarine -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.5/130.5 kB 11.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.5/140.5 kB 9.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 63.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 208.5/208.5 kB 16.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 319.6/319.6 kB 27.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.0/15.0 MB 106.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 66.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 8.0 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.4.5 which is incompatible.

In [2]:
import getpass

COPERNICUS_USERNAME = input("Enter Copernicus Marine username/email: ")
COPERNICUS_PASSWORD = getpass.getpass("Enter Copernicus Marine password: ")

Enter Copernicus Marine username/email: stroresearchadvisor@gmail.com
Enter Copernicus Marine password: ··········

In [3]:
import copernicusmarine
from pathlib import Path

# ============================================================
# Copernicus Marine Global Ocean Waves Reanalysis
# Product: GLOBAL_MULTIYEAR_WAV_001_032
# Dataset: 3-hourly instantaneous wave data
# ============================================================

DATASET_ID = "cmems_mod_glo_wav_my_0.2deg_PT3H-i"

OUTPUT_DIR = Path("copernicusmarine_data/waves_reanalysis")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

BASINS = {
    "bob": {
        "name": "Bay_of_Bengal",
        "minimum_longitude": 80,
        "maximum_longitude": 98,
        "minimum_latitude": 5,
        "maximum_latitude": 22
    },
    "as": {
        "name": "Arabian_Sea",
        "minimum_longitude": 60,
        "maximum_longitude": 75,
        "minimum_latitude": 5,
        "maximum_latitude": 22
    }
}

YEARS = [2020, 2021, 2022, 2023, 2024]

WAVE_VARIABLES = ["VHM0", "VTM02", "VMDR"]


def download_wave_subset(basin_key, year):
    basin = BASINS[basin_key]

    output_filename = f"CMEMS_WAV_{basin_key}_VHM0_VTM02_VMDR_{year}.nc"

    print("\nDownloading wave data")
    print("Basin:", basin["name"])
    print("Year:", year)
    print("Output:", output_filename)

    copernicusmarine.subset(
        username=COPERNICUS_USERNAME,
        password=COPERNICUS_PASSWORD,
        dataset_id=DATASET_ID,
        variables=WAVE_VARIABLES,
        minimum_longitude=basin["minimum_longitude"],
        maximum_longitude=basin["maximum_longitude"],
        minimum_latitude=basin["minimum_latitude"],
        maximum_latitude=basin["maximum_latitude"],
        start_datetime=f"{year}-01-01T00:00:00",
        end_datetime=f"{year}-12-31T23:59:59",
        output_filename=output_filename,
        output_directory=str(OUTPUT_DIR),
        file_format="netcdf",
        netcdf_compression_level=4,
        skip_existing=True
    )


for basin_key in BASINS:
    for year in YEARS:
        download_wave_subset(basin_key, year)

print("All required Copernicus wave reanalysis files downloaded successfully.")

Downloading wave data
Basin: Bay_of_Bengal
Year: 2020
Output: CMEMS_WAV_bob_VHM0_VTM02_VMDR_2020.nc

INFO - 2026-05-16T02:14:45Z - Selected dataset version: "202411"
INFO:copernicusmarine:Selected dataset version: "202411"
INFO - 2026-05-16T02:14:45Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"

  0%|          | [00:00<?]

INFO - 2026-05-16T02:15:36Z - Total size of the download: 131.20 MB.
INFO:copernicusmarine:Total size of the download: 131.20 MB.

Downloading wave data
Basin: Bay_of_Bengal
Year: 2021
Output: CMEMS_WAV_bob_VHM0_VTM02_VMDR_2021.nc

INFO - 2026-05-16T02:15:38Z - Selected dataset version: "202411"
INFO:copernicusmarine:Selected dataset version: "202411"
INFO - 2026-05-16T02:15:38Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"

  0%|          | [00:00<?]

INFO - 2026-05-16T02:16:22Z - Total size of the download: 130.84 MB.
INFO:copernicusmarine:Total size of the download: 130.84 MB.

Downloading wave data
Basin: Bay_of_Bengal
Year: 2022
Output: CMEMS_WAV_bob_VHM0_VTM02_VMDR_2022.nc

INFO - 2026-05-16T02:16:24Z - Selected dataset version: "202411"
INFO:copernicusmarine:Selected dataset version: "202411"
INFO - 2026-05-16T02:16:24Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"

  0%|          | [00:00<?]

INFO - 2026-05-16T02:17:45Z - Total size of the download: 130.84 MB.
INFO:copernicusmarine:Total size of the download: 130.84 MB.

Downloading wave data
Basin: Bay_of_Bengal
Year: 2023
Output: CMEMS_WAV_bob_VHM0_VTM02_VMDR_2023.nc

INFO - 2026-05-16T02:17:48Z - Selected dataset version: "202411"
INFO:copernicusmarine:Selected dataset version: "202411"
INFO - 2026-05-16T02:17:48Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"

  0%|          | [00:00<?]

INFO - 2026-05-16T02:18:29Z - Total size of the download: 130.84 MB.
INFO:copernicusmarine:Total size of the download: 130.84 MB.

Downloading wave data
Basin: Bay_of_Bengal
Year: 2024
Output: CMEMS_WAV_bob_VHM0_VTM02_VMDR_2024.nc

INFO - 2026-05-16T02:18:31Z - Selected dataset version: "202411"
INFO:copernicusmarine:Selected dataset version: "202411"
INFO - 2026-05-16T02:18:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"

  0%|          | [00:00<?]

INFO - 2026-05-16T02:19:12Z - Total size of the download: 131.20 MB.
INFO:copernicusmarine:Total size of the download: 131.20 MB.

Downloading wave data
Basin: Arabian_Sea
Year: 2020
Output: CMEMS_WAV_as_VHM0_VTM02_VMDR_2020.nc

INFO - 2026-05-16T02:19:14Z - Selected dataset version: "202411"
INFO:copernicusmarine:Selected dataset version: "202411"
INFO - 2026-05-16T02:19:14Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"

  0%|          | [00:00<?]

INFO - 2026-05-16T02:19:52Z - Total size of the download: 109.58 MB.
INFO:copernicusmarine:Total size of the download: 109.58 MB.

Downloading wave data
Basin: Arabian_Sea
Year: 2021
Output: CMEMS_WAV_as_VHM0_VTM02_VMDR_2021.nc

INFO - 2026-05-16T02:19:54Z - Selected dataset version: "202411"
INFO:copernicusmarine:Selected dataset version: "202411"
INFO - 2026-05-16T02:19:54Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"

  0%|          | [00:00<?]

INFO - 2026-05-16T02:20:29Z - Total size of the download: 109.28 MB.
INFO:copernicusmarine:Total size of the download: 109.28 MB.

Downloading wave data
Basin: Arabian_Sea
Year: 2022
Output: CMEMS_WAV_as_VHM0_VTM02_VMDR_2022.nc

INFO - 2026-05-16T02:20:31Z - Selected dataset version: "202411"
INFO:copernicusmarine:Selected dataset version: "202411"
INFO - 2026-05-16T02:20:31Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"

  0%|          | [00:00<?]

INFO - 2026-05-16T02:21:38Z - Total size of the download: 109.28 MB.
INFO:copernicusmarine:Total size of the download: 109.28 MB.

Downloading wave data
Basin: Arabian_Sea
Year: 2023
Output: CMEMS_WAV_as_VHM0_VTM02_VMDR_2023.nc

INFO - 2026-05-16T02:21:40Z - Selected dataset version: "202411"
INFO:copernicusmarine:Selected dataset version: "202411"
INFO - 2026-05-16T02:21:40Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"

  0%|          | [00:00<?]

INFO - 2026-05-16T02:22:16Z - Total size of the download: 109.28 MB.
INFO:copernicusmarine:Total size of the download: 109.28 MB.

Downloading wave data
Basin: Arabian_Sea
Year: 2024
Output: CMEMS_WAV_as_VHM0_VTM02_VMDR_2024.nc

INFO - 2026-05-16T02:22:18Z - Selected dataset version: "202411"
INFO:copernicusmarine:Selected dataset version: "202411"
INFO - 2026-05-16T02:22:18Z - Selected dataset part: "default"
INFO:copernicusmarine:Selected dataset part: "default"

  0%|          | [00:00<?]

INFO - 2026-05-16T02:22:52Z - Total size of the download: 109.58 MB.
INFO:copernicusmarine:Total size of the download: 109.58 MB.

All required Copernicus wave reanalysis files downloaded successfully.

In [4]:
from pathlib import Path

folder = Path("copernicusmarine_data/waves_reanalysis")
files = sorted(folder.glob("*.nc"))

print("Total files downloaded:", len(files))

for f in files:
    print(f.name, round(f.stat().st_size / (1024 * 1024), 2), "MB")

Total files downloaded: 10
CMEMS_WAV_as_VHM0_VTM02_VMDR_2020.nc 50.54 MB
CMEMS_WAV_as_VHM0_VTM02_VMDR_2021.nc 49.59 MB
CMEMS_WAV_as_VHM0_VTM02_VMDR_2022.nc 49.81 MB
CMEMS_WAV_as_VHM0_VTM02_VMDR_2023.nc 49.71 MB
CMEMS_WAV_as_VHM0_VTM02_VMDR_2024.nc 49.96 MB
CMEMS_WAV_bob_VHM0_VTM02_VMDR_2020.nc 55.88 MB
CMEMS_WAV_bob_VHM0_VTM02_VMDR_2021.nc 55.13 MB
CMEMS_WAV_bob_VHM0_VTM02_VMDR_2022.nc 55.31 MB
CMEMS_WAV_bob_VHM0_VTM02_VMDR_2023.nc 54.99 MB
CMEMS_WAV_bob_VHM0_VTM02_VMDR_2024.nc 55.42 MB

In [5]:
!pip install xarray netCDF4 pandas pyarrow openpyxl -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 88.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 55.5 MB/s eta 0:00:00

In [6]:
import xarray as xr
import pandas as pd
import numpy as np
from pathlib import Path

INPUT_DIR = Path("copernicusmarine_data/waves_reanalysis")
OUTPUT_DIR = Path("copernicusmarine_data/waves_processed")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Wave energy approximation:
# P ≈ 0.49 × Hs² × T
# Hs = significant wave height, T = mean wave period
def compute_wave_energy(hs, period):
    return 0.49 * (hs ** 2) * period


def infer_basin_from_filename(filename):
    if "_bob_" in filename:
        return "Bay_of_Bengal"
    elif "_as_" in filename:
        return "Arabian_Sea"
    else:
        return "Unknown"


def process_one_wave_file(file_path):
    file_path = Path(file_path)
    print("Processing:", file_path.name)

    basin = infer_basin_from_filename(file_path.name)

    ds = xr.open_dataset(file_path)

    # Convert to dataframe
    df = ds[["VHM0", "VTM02", "VMDR"]].to_dataframe().reset_index()

    # Standardize column names
    df = df.rename(columns={
        "longitude": "lon",
        "latitude": "lat",
        "time": "timestamp",
        "VHM0": "significant_wave_height",
        "VTM02": "mean_wave_period",
        "VMDR": "mean_wave_direction"
    })

    df["basin"] = basin
    df["date"] = pd.to_datetime(df["timestamp"]).dt.date

    # Remove invalid values
    df = df.replace([np.inf, -np.inf], np.nan)
    df = df.dropna(subset=["significant_wave_height", "mean_wave_period"])

    # Derived feature
    df["wave_energy_kw_per_m"] = compute_wave_energy(
        df["significant_wave_height"],
        df["mean_wave_period"]
    )

    # Daily grid-level aggregation
    daily = (
        df.groupby(["basin", "date", "lat", "lon"], as_index=False)
        .agg(
            wave_height_mean=("significant_wave_height", "mean"),
            wave_height_max=("significant_wave_height", "max"),
            wave_height_std=("significant_wave_height", "std"),
            wave_period_mean=("mean_wave_period", "mean"),
            wave_period_max=("mean_wave_period", "max"),
            wave_energy_mean=("wave_energy_kw_per_m", "mean"),
            wave_energy_max=("wave_energy_kw_per_m", "max"),
            wave_direction_mean=("mean_wave_direction", "mean"),
            valid_records=("significant_wave_height", "count")
        )
    )

    ds.close()
    return daily


all_files = sorted(INPUT_DIR.glob("*.nc"))
all_daily_frames = []

for file_path in all_files:
    try:
        daily_df = process_one_wave_file(file_path)
        all_daily_frames.append(daily_df)
    except Exception as e:
        print("Error:", file_path.name)
        print(e)

waves_daily = pd.concat(all_daily_frames, ignore_index=True)

print("Final shape:", waves_daily.shape)
waves_daily.head()

Processing: CMEMS_WAV_as_VHM0_VTM02_VMDR_2020.nc
Processing: CMEMS_WAV_as_VHM0_VTM02_VMDR_2021.nc
Processing: CMEMS_WAV_as_VHM0_VTM02_VMDR_2022.nc
Processing: CMEMS_WAV_as_VHM0_VTM02_VMDR_2023.nc
Processing: CMEMS_WAV_as_VHM0_VTM02_VMDR_2024.nc
Processing: CMEMS_WAV_bob_VHM0_VTM02_VMDR_2020.nc
Processing: CMEMS_WAV_bob_VHM0_VTM02_VMDR_2021.nc
Processing: CMEMS_WAV_bob_VHM0_VTM02_VMDR_2022.nc
Processing: CMEMS_WAV_bob_VHM0_VTM02_VMDR_2023.nc
Processing: CMEMS_WAV_bob_VHM0_VTM02_VMDR_2024.nc
Final shape: (22530564, 13)

,basin,date,lat,lon,wave_height_mean,wave_height_max,wave_height_std,wave_period_mean,wave_period_max,wave_energy_mean,wave_energy_max,wave_direction_mean,valid_records
0,Arabian_Sea,2020-01-01,5.0,60.000000,1.22125,1.28,0.079181,4.74375,4.93,3.486810,3.861545,58.22375,8
1,Arabian_Sea,2020-01-01,5.0,60.200001,1.21750,1.27,0.073241,4.80375,5.03,3.506671,3.851094,60.42500,8
2,Arabian_Sea,2020-01-01,5.0,60.400002,1.21875,1.26,0.067705,4.84750,5.11,3.543272,3.912344,62.60000,8
3,Arabian_Sea,2020-01-01,5.0,60.599998,1.22000,1.27,0.062792,4.88625,5.18,3.576071,3.902736,64.08125,8
4,Arabian_Sea,2020-01-01,5.0,60.799999,1.21750,1.26,0.054707,4.92375,5.24,3.586676,3.947942,64.36625,8

In [8]:
from pathlib import Path

OUTPUT_DIR = Path("copernicusmarine_data/waves_processed")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

final_csv = OUTPUT_DIR / "copernicus_waves_daily_grid_bob_as_2020_2024.csv"
final_parquet = OUTPUT_DIR / "copernicus_waves_daily_grid_bob_as_2020_2024.parquet"

# Save full dataset
waves_daily.to_csv(final_csv, index=False)
waves_daily.to_parquet(final_parquet, index=False)

print("Full CSV saved:", final_csv)
print("Full Parquet saved:", final_parquet)
print("Rows:", len(waves_daily))

Full CSV saved: copernicusmarine_data/waves_processed/copernicus_waves_daily_grid_bob_as_2020_2024.csv
Full Parquet saved: copernicusmarine_data/waves_processed/copernicus_waves_daily_grid_bob_as_2020_2024.parquet
Rows: 22530564

In [9]:
import numpy as np
import pandas as pd
from pathlib import Path

OUTPUT_DIR = Path("copernicusmarine_data/waves_processed")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

df = waves_daily.copy()

# Convert date
df["date"] = pd.to_datetime(df["date"])

# Circular mean preparation for wave direction
df["wave_dir_sin"] = np.sin(np.deg2rad(df["wave_direction_mean"]))
df["wave_dir_cos"] = np.cos(np.deg2rad(df["wave_direction_mean"]))

waves_basin_daily = (
    df.groupby(["basin", "date"], as_index=False)
    .agg(
        wave_height_mean=("wave_height_mean", "mean"),
        wave_height_max=("wave_height_max", "max"),
        wave_height_std=("wave_height_mean", "std"),
        wave_period_mean=("wave_period_mean", "mean"),
        wave_period_max=("wave_period_max", "max"),
        wave_energy_mean=("wave_energy_mean", "mean"),
        wave_energy_max=("wave_energy_max", "max"),
        valid_grid_cells=("valid_records", "count"),
        total_valid_records=("valid_records", "sum"),
        wave_dir_sin_mean=("wave_dir_sin", "mean"),
        wave_dir_cos_mean=("wave_dir_cos", "mean")
    )
)

# Convert circular mean back to degrees
waves_basin_daily["wave_direction_mean"] = (
    np.rad2deg(
        np.arctan2(
            waves_basin_daily["wave_dir_sin_mean"],
            waves_basin_daily["wave_dir_cos_mean"]
        )
    ) + 360
) % 360

waves_basin_daily = waves_basin_daily.drop(
    columns=["wave_dir_sin_mean", "wave_dir_cos_mean"]
)

# Save compact summary
summary_csv = OUTPUT_DIR / "copernicus_waves_basin_daily_summary_2020_2024.csv"
summary_excel = OUTPUT_DIR / "copernicus_waves_basin_daily_summary_2020_2024.xlsx"
summary_parquet = OUTPUT_DIR / "copernicus_waves_basin_daily_summary_2020_2024.parquet"

waves_basin_daily.to_csv(summary_csv, index=False)
waves_basin_daily.to_excel(summary_excel, index=False)
waves_basin_daily.to_parquet(summary_parquet, index=False)

print("Summary rows:", len(waves_basin_daily))
print("Saved Excel summary:", summary_excel)

waves_basin_daily.head()

Summary rows: 3654
Saved Excel summary: copernicusmarine_data/waves_processed/copernicus_waves_basin_daily_summary_2020_2024.xlsx

,basin,date,wave_height_mean,wave_height_max,wave_height_std,wave_period_mean,wave_period_max,wave_energy_mean,wave_energy_max,valid_grid_cells,total_valid_records,wave_direction_mean
0,Arabian_Sea,2020-01-01,0.874848,1.58,0.213309,4.707214,7.40,1.884020,6.558552,6087,48696,68.648040
1,Arabian_Sea,2020-01-02,0.870569,1.79,0.194276,4.352296,7.70,1.729883,7.991346,6087,48696,71.700048
2,Arabian_Sea,2020-01-03,1.097519,1.78,0.235370,4.171245,7.46,2.674221,7.560753,6087,48696,48.187286
3,Arabian_Sea,2020-01-04,1.134751,1.93,0.269329,4.354434,7.19,3.002819,9.071249,6087,48696,43.741211
4,Arabian_Sea,2020-01-05,1.066920,1.80,0.259714,4.467586,6.93,2.730207,8.308691,6087,48696,45.205004

In [10]:
import shutil
from google.colab import files

zip_name = "copernicus_waves_bob_as_2020_2024"

shutil.make_archive(zip_name, "zip", "copernicusmarine_data/waves_reanalysis")

files.download(zip_name + ".zip")

In [11]:
import shutil
from google.colab import files

zip_name = "copernicus_waves_processed_daily_bob_as_2020_2024"

shutil.make_archive(zip_name, "zip", "copernicusmarine_data/waves_processed")

files.download(zip_name + ".zip")